# nixpacks.toml

[phases.setup]
# Add apt packages needed for OpenCV
[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0"

# You might only need libgl1-mesa-glx, but libglib2.0-0 is also commonly needed by OpenCV
# Try with just libgl1-mesa-glx first if you prefer minimal dependencies.